In [1]:
a = 2
b = 0
c = 3
d = 4
arr = ['+','-','+', a,b,c,d]

In [2]:
from math import log2

log2(len(arr)+1)

3.0

In [3]:
import numpy as np

# arr = np.array([[[a,b], [c,d]]],dtype=np.float32)
arr = np.array([a,b,c,d], dtype=np.float32)
arr

array([2., 0., 3., 4.], dtype=float32)

In [4]:
arr[::2] + np.roll(arr,-1)[::2]

array([2., 7.], dtype=float32)

In [5]:
l3_arr = l2_arr + np.roll(l2_arr, -2)
l3_arr

NameError: name 'l2_arr' is not defined

In [17]:
def operate(a, operation):
    left = a[::2]
    right = np.roll(a,-1)[::2]

    # print('LR:',left, right)

    add = left + right
    sub = left - right

    result = operation[:,0] * add
    result += operation[:,1] * sub

    # print( operation[:,0] , add)
    # print( operation[:,1] , sub)

    return result
a1 = arr
op1 = np.array([
    [1,0],
    [0,1]
],dtype=np.float32)
print('a1',a1)
a2 = operate(arr, op1)
print('a2',a2)
op2 = np.array([
    [1,0],
],dtype=np.float32)
a3 = operate(a2, op2)
print('a3',a3)

a1 [2. 0. 3. 4.]
a2 [ 2. -1.]
a3 [1.]


[2. 7.]
[ 0. -0.]
[2. 0. 3. 4.] [2. 7.]


In [1]:
import tensorflow as tf

In [2]:
a = tf.Variable([1,2,3],dtype=tf.float32)
b = tf.constant([4,5,6],dtype=tf.float32)

In [4]:
c = tf.concat([a,b], axis=0)
c

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [9]:
with tf.GradientTape() as tape:
    c = tf.concat([a,b], axis=0)

tape.gradient(c, a)
# tape.gradient(c, b)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>